### ISSUE TITLE
Support Multiple datastore types

### ISSUE THREAD

**Issue by xarnze** [opennota/widdly#2]
Hi,

I've been working on adding support for other datastore providers here https://github.com/xarnze/widdly 

So far I've added sqlite support, I'm also looking at adding support for the multi-file structure that you get in TW2 on node. That would allow for easier migration from the node.js server side.

**Comment by opennota** [comment]
Well, SQLite datastore was the first I implemented (it never made it to GitHub, but I have a local copy).

It should be easy to replace the provider. One just needs to replace `	_ "github.com/opennota/widdly/store/bolt"` in `main.go` with the import of the desired datastore.

Is the multi-file structure somehow different? Is the `TiddlerStore` interface not enough in that case?

**Comment by xarnze** [comment]
Nope the TiddlerStore interface should work for just about anything I think. It'll just be a different datastore backend. It'd potentially be good to be able to pick which data store to use with a command line flag.

**Comment by opennota** [comment]
My concern is that having SQLite backend included by default would probably make the repository not go-gettable for windows users (because of cgo).

**Comment by xarnze** [comment]
Yep fair point, no worries :)
